---
# TODO: package this?
- name: Copy static master exec scripts
  copy:
    src: "scripts/{{ l_runtime }}/master-exec"
    dest: "/usr/local/bin/"
    mode: 0500
  vars:
    l_runtime: "{{ 'crio' if openshift_use_crio | default(False) else 'docker' }}"

- name: Copy needed master api scripts
  template:
    src: "{{ item }}.j2"
    dest: "/usr/local/bin/{{ openshift_service_type }}-{{ item }}"
  with_items:
  - master-api
  - master-controllers
  - master-etcd

- name: Ensure cri-tools installed
  package:
    name: cri-tools
    state: present
  when: openshift_use_crio | default(False)
