---
# TODO: package this?
- name: Copy static master exec scripts
  copy:
    src: "scripts/{{ l_runtime }}/master-exec"
    dest: "/usr/local/bin/"
    mode: 0500
  vars:
    l_runtime: "{{ 'crio' if openshift_use_crio | default(False) else 'docker' }}"

- name: Copy needed master api scripts
  template:
    src: "master-script.j2"
    dest: "/usr/local/bin/{{ openshift_service_type }}-{{ item.name }}"
    mode: 0755
  vars:
    static_pod_filename: "{{ item.static_pod_filename }}"
    service: "{{ item.service }}"
  with_items:
  - name: api
    service: master-api
    static_pod_filename: apiserver
  - name: controllers
    service: master-controllers
    static_pod_filename: controller
  - name: etcd
    service: master-etcd
    static_pod_filename: etcd

- name: Ensure cri-tools installed
  package:
    name: cri-tools
    state: present
  when: openshift_use_crio | default(False)
