---
- name: Install master services files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ openshift_service_type }}-{{ item }}"
    owner: root
    group: root
    mode: 600
  with_items:
  - master-api.service
  - master-controllers.service
  - master-etcd.service
  notify:
  - reload systemd units

- name: Enable service files
  service:
    name: "{{ openshift_service_type }}-{{ item }}"
    enabled: true
  with_items:
  - master-api
  - master-controllers
  - master-etcd
