---
- name: Evaluate node groups
  hosts: localhost
  connection: local
  tasks:
  - name: Evaluate oo_containerized_master_nodes
    add_host:
      name: "{{ item }}"
      groups: oo_containerized_master_nodes
      ansible_ssh_user: "{{ g_ssh_user | default(omit) }}"
      ansible_become: "{{ g_sudo | default(omit) }}"
    with_items: "{{ groups.oo_nodes_to_config | default([]) }}"
    when:
    - hostvars[item].openshift is defined
    - hostvars[item].openshift.common is defined
    - hostvars[item].openshift_is_containerized | bool
    - (item in groups.oo_nodes_to_config and item in groups.oo_masters_to_config)
    changed_when: False

  - name: Evaluate oo_exclude_nodes_to_config as all nodes that have already been bootstrapped
    add_host:
      name: "{{ item }}"
      groups: oo_exclude_nodes_to_config
      ansible_ssh_user: "{{ g_ssh_user | default(omit) }}"
      ansible_become: "{{ g_sudo | default(omit) }}"
    with_items: "{{ groups.oo_nodes_to_config | default([]) }}"
    when:
    - hostvars[item].openshift is defined
    - hostvars[item].openshift.common is defined
    - hostvars[item].openshift_is_bootstrapped | bool
    changed_when: False

- name: Disable excluders
  hosts: oo_nodes_to_config:!oo_exclude_nodes_to_config
  gather_facts: no
  roles:
  - role: openshift_excluder
    r_openshift_excluder_action: disable
