---
# set facts
- include_tasks: facts.yaml

# namespace
- name: Add prometheus project
  oc_project:
    state: present
    name: "{{ openshift_prometheus_namespace }}"
    node_selector: ""
    description: Prometheus

- name: Make temp directory for node exporter template
  command: mktemp -d /tmp/prometheus-ansible-XXXXXX
  register: mktemp
  changed_when: False

# create clusterrolebinding for prometheus-node-exporter serviceaccount
- name: Set hostaccess SCC for prometheus-node-exporter
  oc_adm_policy_user:
    state: present
    namespace: "{{ openshift_prometheus_namespace }}"
    resource_kind: scc
    resource_name: hostaccess
    user: "system:serviceaccount:{{ openshift_prometheus_namespace }}:prometheus-node-exporter"

- name: Copy node exporter templates to temp directory
  copy:
    src: "{{ item }}"
    dest: "{{ mktemp.stdout }}/{{ item }}"
  with_items:
    - "{{ __node_exporter_template_file }}"

- name: Create node exporter template
  oc_obj:
    namespace: "{{ openshift_prometheus_namespace }}"
    name: prometheus-node-exporter
    kind: Template
    files:
      - "{{ mktemp.stdout }}/{{ __node_exporter_template_file }}"

- name: Apply the template
  oc_process:
    namespace: "{{ openshift_prometheus_namespace }}"
    template_name: prometheus-node-exporter
    params:
      IMAGE: "{{ l_openshift_prometheus_node_exporter_image_prefix }}prometheus-node-exporter:{{ l_openshift_prometheus_node_exporter_image_version }}"
      MEMORY_REQUESTS: "{{ openshift_prometheus_node_exporter_memory_requests }}"
      CPU_REQUESTS: "{{ openshift_prometheus_node_exporter_cpu_requests }}"
      MEMORY_LIMITS: "{{ openshift_prometheus_node_exporter_memory_limit }}"
      CPU_LIMITS: "{{ openshift_prometheus_node_exporter_cpu_limit }}"

- name: Remove temp directory
  file:
    state: absent
    name: "{{ mktemp.stdout }}"
  changed_when: False
