---
- name: Delete router service
  oc_obj:
    kind: svc
    state: absent
    name: "{{ item['name'] }}"
    namespace: "{{ item['namespace'] }}"
  with_items: "{{ openshift_hosted_routers }}"
  when:
  - openshift_hosted_routers | length > 0

- name: Delete router deployment config
  oc_obj:
    kind: dc
    state: absent
    name: "{{ item['name'] }}"
    namespace: "{{ item['namespace'] }}"
  with_items: "{{ openshift_hosted_routers }}"
  when:
  - openshift_hosted_routers | length > 0

- include_tasks: router.yml
