---
- name: Install clients
  package:
    name: "{{ openshift_service_type }}-clients{{ openshift_pkg_version | default('') }}"
    state: present
  register: result
  until: result is succeeded

- block:
  - name: Pull CLI Image
    docker_image:
      name: "{{ openshift_cli_image }}"
    when: not openshift_use_crio_only | bool

- name: Install bash completion for oc tools
  package:
    name: bash-completion
    state: present
  register: result
  until: result is succeeded
