---
- name: Ensure project exists
  oc_project:
    name: kube-proxy-and-dns
    state: present
    node_selector:
      - ""

- name: Make temp directory for templates
  command: mktemp -d /tmp/ansible-XXXXXX
  register: mktemp
  changed_when: False

- name: Render templates to temp directory
  template:
    src: "{{ item }}"
    dest: "{{ mktemp.stdout }}/{{ item | basename | splitext | first }}.yaml"
  with_fileglob:
    - "templates/*.yaml"

- name: Ensure the service account can run privileged
  oc_adm_policy_user:
    namespace: "kube-proxy-and-dns"
    resource_kind: scc
    resource_name: privileged
    state: present
    user: "system:serviceaccount:kube-proxy-and-dns:proxy"

# TODO: temporary until we fix apply for image stream tags
- name: Remove the image stream tag
  oc_obj:
    name: "{{ node_tag_name }}"
    kind: istag
    state: absent
    namespace: kube-proxy-and-dns

- name: Apply the config
  shell: >
    {{ openshift_client_binary }} --config={{ openshift.common.config_base }}/master/admin.kubeconfig apply -f "{{ mktemp.stdout }}"
  register: kube_dns_apply_result
  failed_when:
    - kube_dns_apply_result.rc != 0
    - "'AlreadyExists' not in kube_dns_apply_result.stderr"
  changed_when: "'AlreadyExists' not in kube_dns_apply_result.stderr"

- name: Remove temp directory
  file:
    state: absent
    name: "{{ mktemp.stdout }}"
  changed_when: False
