---
# PREREQ Node service is ready to run static pods

# INPUT r_etcd_upgrade_version

- include_tasks: runtime.yml

- name: Verify cluster is healthy pre-upgrade
  command: "{{ etcdctlv2 }} cluster-health"

- name: Remove old etcd service files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "/etc/systemd/system/etcd.service"
  - "/etc/systemd/system/etcd_container.service"

# We removed the ability to detect what was previously 'containerized'
# Need to stop and disable this service, but might not be present.
- name: Stop, disable and mask old etcd service
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    masked: yes
    daemon_reload: yes
  with_items:
  - etcd
  - etcd_container
  failed_when: False

- name: Remove etcd system container
  oc_atomic_container:
    name: etcd_container
    image: "{{ etcd_image }}"
    state: absent

- name: Systemd reload configuration
  systemd:
    name: etcd_container
    daemon_reload: yes

- name: Reload systemd daemon
  command: "systemctl daemon-reload"

- name: Configure static definition
  import_tasks: static.yml

- include_tasks: runtime.yml

- name: Verify cluster is healthy
  command: "{{ etcdctlv2 }} cluster-health"
  register: etcdctl
  until: etcdctl.rc == 0
  retries: 30
  delay: 10
