---
- block:
  - name: Record RPM based etcd version
    command: rpm -qa --qf '%{version}' etcd\*
    args:
      warn: no
    register: etcd_rpm_version
    failed_when: false
    # AUDIT:changed_when: `false` because we are only inspecting
    # state, not manipulating anything
    changed_when: false
  - debug:
      msg: "Etcd rpm version {{ etcd_rpm_version.stdout }} detected"
  when:
  - not openshift_is_containerized | bool

- block:
  - name: Record containerized etcd version
    command: "{{ r_etcd_container_version_command }}"
    register: etcd_container_version_result
    failed_when: false
    # AUDIT:changed_when: `false` because we are only inspecting
    # state, not manipulating anything
    changed_when: false

  - set_fact:
      etcd_container_version: "{{ etcd_container_version_result.stdout }}"

  - debug:
      msg: "Etcd containerized version {{ etcd_container_version }} detected"
  when:
  - openshift_is_containerized | bool
