---
# NOTE: These steps should only be run against masters and nodes.
- name: Ensure the requested version packages are available.
  hosts: "{{ l_openshift_version_check_hosts | default('oo_nodes_to_config:oo_masters_to_config:!oo_first_master') }}"
  tasks:
  - include_role:
      name: openshift_version
      tasks_from: masters_and_nodes.yml
