---
- name: Create temp directory for doing work in on target
  command: mktemp -td openshift-cluster-monitoring-ansible-XXXXXX
  register: mktemp
  changed_when: False

- name: Copy files to temp directory
  copy:
    src: "{{ item }}"
    dest: "{{ mktemp.stdout }}/{{ item }}"
  with_items:
  - cluster-monitoring-operator.yaml

- name: Copy admin client config
  command: >
    cp {{ openshift.common.config_base }}/master/admin.kubeconfig {{ mktemp.stdout }}/admin.kubeconfig
  changed_when: false

- name: Add monitoring project
  oc_project:
    state: present
    name: openshift-monitoring
    description: Openshift Monitoring
    node_selector: ""

- name: Create the template
  oc_obj:
    namespace: openshift-monitoring
    name: openshift-cluster-monitoring-operator
    kind: Template
    files:
    - "{{ mktemp.stdout }}/cluster-monitoring-operator.yaml"

- name: Apply the template
  oc_process:
    namespace: openshift-monitoring
    template_name: openshift-cluster-monitoring-operator
    params:
      OPERATOR_IMAGE: "{{ openshift_cluster_monitoring_operator_image }}"
      PROMETHEUS_OPERATOR_IMAGE: "{{ openshift_cluster_monitoring_operator_prometheus_operator_repo }}"
      ALERTMANAGER_IMAGE: "{{ openshift_cluster_monitoring_operator_alertmanager_repo }}"
      PROMETHEUS_IMAGE: "{{ openshift_cluster_monitoring_operator_prometheus_repo }}"
      CONFIG_RELOADER_IMAGE: "{{ openshift_cluster_monitoring_oeprator_configmap_reloader_repo }}"
      ALERTMANAGER_CONFIG: "{{ openshift_cluster_monitoring_operator_alertmanager_config | b64encode }}"
      CLUSTER_ID: "{{ openshift_cluster_monitoring_operator_cluster_id }}"

- name: Delete temp directory
  file:
    name: "{{ mktemp.stdout }}"
    state: absent
  changed_when: False
