---
# This playbook waits for registry and router pods after both have been
# created.  It is intended to allow the tasks of deploying both to complete
# before polling to save time.
- name: Poll for hosted pod deployments
  hosts: oo_first_master
  tasks:
  # Need to set_fact variable for registry.
  - import_role:
      name: openshift_hosted
      tasks_from: set_fact_workaround.yml
  - import_role:
      name: openshift_hosted
      tasks_from: deployment.yml
    vars:
      l_namespace: default
      l_deployment_name: router
      l_kind: deploymentconfig
      l_kubeconfig_path: "{{ openshift.common.config_base }}/master/admin.kubeconfig"
      l_component: "Router"
    when:
    - openshift_hosted_manage_router | default(True) | bool
    - openshift_hosted_router_registryurl is defined

  - import_role:
      name: openshift_hosted
      tasks_from: deployment.yml
    vars:
      l_namespace: default
      l_deployment_name: docker-registry
      l_kind: deploymentconfig
      l_kubeconfig_path: "{{ openshift.common.config_base }}/master/admin.kubeconfig"
      l_component: "Docker registry"
    when:
    - openshift_hosted_manage_registry | default(True) | bool
    - openshift_hosted_registry_registryurl is defined
