---
# Generate config using openshift-installer, set Base Domain to <master IP>.xip.io
# Add all hosts in [nodes] group
# Set ignition_file for bootstrap host only
# Add boostrap host to [bootstrap] group

- import_playbook: init/main.yml
  vars:
    l_install_base_packages: True
    l_repo_hosts: "all:!all"

# This is required for container runtime for crio, only needs to run once.
- name: Configure os_firewall
  hosts: "{{ l_scale_up_hosts | default(l_default_firewall_hosts) }}"
  vars:
    l_default_firewall_hosts: "oo_masters_to_config:oo_etcd_to_config:oo_lb_to_config:oo_nfs_to_config:oo_nodes_to_config"
  roles:
  - role: os_firewall

- import_playbook: container-runtime/private/setup_storage.yml

- import_playbook: container-runtime/private/config.yml

- name: install nodes
  hosts: nodes
  tasks:
  - import_role:
      name: openshift_node40
      tasks_from: install.yml

- name: setup AWS creds
  hosts: masters:bootstrap
  tasks:
  - import_role:
      name: openshift_node40
      tasks_from: aws.yml

- name: Config bootstrap node
  hosts: bootstrap
  tasks:
  - import_role:
      name: openshift_node40
      tasks_from: aws.yml
  - import_role:
      name: openshift_node40
      tasks_from: config.yml
  - import_role:
      name: openshift_node40
      tasks_from: systemd.yml

- name: Config masters
  hosts: masters
  tasks:
  # TODO Read this from master's ignition file
  - set_fact:
      openshift_bootstrap_endpoint: "https://{{ hostvars[groups['bootstrap'][0]]['ansible_host'] }}:49500/config/master?etcd_index=0"
  - name: Wait for bootstrap endpoint to show up
    uri:
      url: "{{ openshift_bootstrap_endpoint }}"
      validate_certs: false
    delay: 10
    retries: 60
    register: result
    until:
      - "'status' in result"
      - result.status == 200
  - import_role:
      name: openshift_node40
      tasks_from: config.yml
  - import_role:
      name: openshift_node40
      tasks_from: systemd.yml

- name: start services on all nodes
  hosts: nodes
  tasks:
  # TODO Read this from master's ignition file
  - set_fact:
      openshift_bootstrap_endpoint: "https://{{ hostvars[groups['bootstrap'][0]]['ansible_host'] }}:49500/config/worker"
  - name: Wait for bootstrap endpoint to show up
    uri:
      url: "{{ openshift_bootstrap_endpoint }}"
      validate_certs: false
    delay: 10
    retries: 60
    register: result
    until:
      - "'status' in result"
      - result.status == 200
  - import_role:
      name: openshift_node40
      tasks_from: config.yml
  - import_role:
      name: openshift_node40
      tasks_from: systemd.yml
